# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gestion-licencia
    volumes:
      - ./database:/var/lib/mysql
      - ./script:/docker-entrypoint-initdb.d